# trusty beta image has jdk8, gcc4.8.4
dist: trusty
sudo: required
# Not technically required but suppresses 'Ruby' in Job status message.
language: go
python:
  - "2.7"
os:
  - linux

go:
  - 1.10.x

jdk:
  - oraclejdk8

addons:
  apt:
    sources:
      - sourceline: 'deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8'
        key_url: 'https://storage.googleapis.com/bazel-apt/doc/apt-key.pub.gpg'
    packages:
      - bazel

install:
  - export PATH=$PATH:$HOME/bin && mkdir -p $HOME/bin
  - wget https://github.com/bazelbuild/buildtools/releases/download/0.11.1/buildifier && chmod +x buildifier && mv buildifier $HOME/bin/
  - sudo pip install pylint

jobs:
  include:
    - stage: fetch
      script: bazel fetch //...
    - stage: build 
      script: bazel build --noshow_progress --noshow_loading_progress --test_output=errors //...
    - stage: test
      script: bazel test --test_output=errors //...
    - stage: deploy
      script: bazel run push_nonroot push_debug push_static

  

notifications:
  email: false
